@echo off
setlocal
set "CSC=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if not exist "%CSC%" exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /out:"%~dp0tests\FormulaEngineTests.exe" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0tests\FormulaEngineTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\FormulaEngineTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /out:"%~dp0tests\FormulaEngineV5Tests.exe" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0tests\FormulaEngineV5Tests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\FormulaEngineV5Tests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /out:"%~dp0tests\CsvFileTests.exe" "%~dp0CsvFile.cs" "%~dp0tests\CsvFileTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\CsvFileTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.OpenFileTests /out:"%~dp0tests\OpenFileTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\OpenFileTests.cs" /resource:"%~dp0vendor\Jint.dll",Jint.dll /resource:"%~dp0vendor\Acornima.dll",Acornima.dll /resource:"%~dp0vendor\System.Memory.dll",System.Memory.dll /resource:"%~dp0vendor\System.Runtime.CompilerServices.Unsafe.dll",System.Runtime.CompilerServices.Unsafe.dll /resource:"%~dp0vendor\System.Buffers.dll",System.Buffers.dll /resource:"%~dp0vendor\System.Numerics.Vectors.dll",System.Numerics.Vectors.dll
if errorlevel 1 exit /b 1
"%~dp0tests\OpenFileTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.XlsxFileTests /out:"%~dp0tests\XlsxFileTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\XlsxFileTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\XlsxFileTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.MultiSheetTests /out:"%~dp0tests\MultiSheetTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\MultiSheetTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\MultiSheetTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.InterchangeTests /out:"%~dp0tests\InterchangeTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\PdfSharp.dll",PdfSharp.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\InterchangeTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\InterchangeTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.V3UiTests /out:"%~dp0tests\V3UiTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\V3UiTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\V3UiTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.VisualUiTests /out:"%~dp0tests\VisualUiTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\VisualUiTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\VisualUiTests.exe"
if errorlevel 1 exit /b 1
"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.V4UiTests /out:"%~dp0tests\V4UiTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\V4UiTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\V4UiTests.exe"
if errorlevel 1 exit /b 1

"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.DataToolsTests /out:"%~dp0tests\DataToolsTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\DataToolsTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\DataToolsTests.exe"
if errorlevel 1 exit /b 1

"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.TablePivotTests /out:"%~dp0tests\TablePivotTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\TablePivotTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\TablePivotTests.exe"
if errorlevel 1 exit /b 1

"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.LargeDataTests /out:"%~dp0tests\LargeDataTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\LargeDataTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\LargeDataTests.exe"
if errorlevel 1 exit /b 1

"%CSC%" /nologo /codepage:65001 /target:exe /main:DinkCel.ChartPrintTests /out:"%~dp0tests\ChartPrintTests.exe" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Xml.Linq.dll /reference:System.Core.dll /reference:System.IO.Compression.dll /reference:System.IO.Compression.FileSystem.dll /reference:"%~dp0vendor\NPOI.dll" /resource:"%~dp0vendor\NPOI.dll",NPOI.dll /resource:"%~dp0vendor\ICSharpCode.SharpZipLib.dll",ICSharpCode.SharpZipLib.dll /reference:"%~dp0vendor\PdfSharp.dll" /resource:"%~dp0vendor\PdfSharp.dll",PdfSharp.dll /reference:System.Windows.Forms.DataVisualization.dll /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:System.Security.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" "%~dp0DesktopApp.cs" "%~dp0WorkbookFeatures.cs" "%~dp0EmbeddedDependencies.cs" "%~dp0XlsFile.cs" "%~dp0OdsFile.cs" "%~dp0PdfFile.cs" "%~dp0SpreadsheetV3Ui.cs" "%~dp0SpreadsheetOutputUi.cs" "%~dp0SpreadsheetEditingUi.cs" "%~dp0SpreadsheetFormatting.cs" "%~dp0SpreadsheetFeatures.cs" "%~dp0DataTools.cs" "%~dp0TablePivotUi.cs" "%~dp0PivotEngine.cs" "%~dp0PivotUi.cs" "%~dp0ChartRendering.cs" "%~dp0ChartEditorUi.cs" "%~dp0ChartOverlayUi.cs" "%~dp0PrintLayout.cs" "%~dp0PrintSetupUi.cs" "%~dp0XlsxFile.cs" "%~dp0XlsxStyles.cs" "%~dp0XlsxCharts.cs" "%~dp0XlsxChartsV9.cs" "%~dp0FormulaEngine.cs" "%~dp0FormulaEngineV5.cs" "%~dp0ThemePalette.cs" "%~dp0DinkVisualUi.cs" "%~dp0CsvFile.cs" "%~dp0DinkScript.cs" "%~dp0DinkScriptUi.cs" "%~dp0tests\ChartPrintTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\ChartPrintTests.exe"
if errorlevel 1 exit /b 1

"%CSC%" /nologo /codepage:65001 /target:exe /out:"%~dp0tests\DinkScriptTests.exe" /reference:System.Web.Extensions.dll /reference:System.Numerics.dll /reference:"%~dp0vendor\Jint.dll" /reference:"%~dp0vendor\Acornima.dll" /resource:"%~dp0vendor\Jint.dll",Jint.dll /resource:"%~dp0vendor\Acornima.dll",Acornima.dll /resource:"%~dp0vendor\System.Memory.dll",System.Memory.dll /resource:"%~dp0vendor\System.Runtime.CompilerServices.Unsafe.dll",System.Runtime.CompilerServices.Unsafe.dll /resource:"%~dp0vendor\System.Buffers.dll",System.Buffers.dll /resource:"%~dp0vendor\System.Numerics.Vectors.dll",System.Numerics.Vectors.dll "%~dp0EmbeddedDependencies.cs" "%~dp0DinkScript.cs" "%~dp0tests\DinkScriptTests.cs"
if errorlevel 1 exit /b 1
"%~dp0tests\DinkScriptTests.exe"
if errorlevel 1 exit /b 1
